import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Root } from "@/components/telegram-provider";
import Awaiter from "@/components/Awaiter";
import "@telegram-apps/telegram-ui/dist/styles.css";
import "normalize.css/normalize.css";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import { isUserId } from "@/context";
import { postEvent, request } from "@telegram-apps/sdk";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<script src="https://telegram.org/js/telegram-web-app.js" async />
			</head>
			<body
				className={`${inter.className} scroll-smooth`}
				cz-shortcut-listen="true"
			>
				<Awaiter />
				<ConvexClientProvider>
					<Root>
						<div
							id="root"
							className="w-full h-screen  overflow-y-auto text-white"
						>
							<div className="h-full overflow-y-auto  pt-0 bg-[#212121]">
								<div className="grid h-full overflow-y-auto min-h-svh">
									{children}
								</div>
							</div>
						</div>
					</Root>
				</ConvexClientProvider>
			</body>
		</html>
	);
}
